version: "3.8"
services:
  gateway:
    build: ./gateway
    restart: always
    ports:
      - 3000:3000
    networks:
      - micronet
  post_db:
    image: postgres:16.4
    # restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: library
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - micronet
  game:
    build: ./game-service
    restart: always
    depends_on:
      - post_db
    networks:
      - micronet
    ports:
      - 3002:3002

networks:
  micronet:
    driver: bridge
